[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "GraphGen"
authors = [{name = "Zihong Chen", email = "chenzihong@pjlab.org.cn"}]
dynamic = ["version", "description"]
